return {
    id = "ColorsPlusProbe",
    name = "Colors+ Probe",
    version = "0.2.119",
    description = "Optional shortcuts for the color picker. You can also use the Custom Color button directly in character customization. The diagnostic tools are only needed when asked to help investigate a problem.",
    actions = {
        { key = "open_picker", name = "Open live color picker", category = "Colors+ Picker", danger = true,
          desc = "First open the color choices for the part you want to customize, then use this to choose your own color. Some scar options have adjustment sliders instead. Nothing is saved automatically. Performance logging runs until you close the picker and goes into colors_plus_performance.log." },
        { key = "apply_picker", name = "Apply picker color", category = "Colors+ Picker", danger = true,
          desc = "Keep the color you've chosen and close the picker. Save your character normally when you're happy with your changes." },
        { key = "close_picker", name = "Cancel / close picker", category = "Colors+ Picker",
          desc = "Close the picker and return to the color you had when you opened it. Use Restore original appearance if you also want to undo colors you already applied." },
        { key = "restore_tint", name = "Restore original appearance", category = "Colors+ Picker",
          desc = "Close the picker and undo the custom-color edits it is tracking for this editing session. This does not undo changes you've already saved to your character." },
        { key = "capture_compat", name = "Capture color compatibility", category = "Colors+ Diagnostics",
          desc = "Only use if asked. Records information about the color choices you're viewing to help investigate unsupported colors. Use Restore original appearance first, then open the affected color choices. This tool does not change colors." },
        { key = "inspect_tint", name = "Inspect tint target", category = "Colors+ Diagnostics",
          desc = "Only use if asked. Open the affected color choices first. Records what the selected color controls, without changing it." },
        { key = "trace_screens", name = "Trace screen transitions (60 seconds)", category = "Colors+ Diagnostics",
          desc = "Only use if asked. Records information as you move between customization screens for 60 seconds. Close Dev Panel after starting, then repeat the steps that caused the problem. Does not change colors." },
        { key = "stop_screen_trace", name = "Stop screen trace", category = "Colors+ Diagnostics",
          desc = "Stop recording screen changes early. Does not change your colors or stop the normal performance log." },
        { key = "trace_stock_calls", name = "Trace stock hover calls (60 seconds)", category = "Colors+ Diagnostics",
          desc = "Only use if asked. Use Restore original appearance first, start this recording, then move your mouse over the game's existing color choices. The custom picker is unavailable during this 60-second recording." },
        { key = "stop_stock_calls", name = "Stop stock hover trace", category = "Colors+ Diagnostics",
          desc = "Stop recording color previews early so you can use the custom picker again. Does not change your appearance." },
        { key = "trace_materials", name = "Trace materials (60 seconds)", category = "Colors+ Diagnostics",
          desc = "Only use if asked. Records extra information about how the selected appearance is drawn for 60 seconds. Does not change colors." },
        { key = "stop_material_trace", name = "Stop material trace", category = "Colors+ Diagnostics",
          desc = "Stop this extra recording early. Leaves the picker and its automatic performance log alone." },
    },
}
